Repository DFE-Digital/itt-mentor-services, pull requests merged in 2024-04, with the labels that each got.

#424 Fix claim back links
  app/controllers/claims/schools/claims_controller.rb
  app/forms/claim/mentor_training_form.rb
  app/models/claims/claim.rb
  app/services/claims/claim/remove_empty_mentor_training_hours.rb
  spec/factories/mentor_trainings.rb
  spec/models/claims/claim_spec.rb
  spec/services/claims/claim/remove_empty_mentor_training_hours_spec.rb
  spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb
Labels: deploy

#440 Add external link to the feedback form
  app/helpers/routes_helper.rb
  app/views/claims/pages/feedback.html.erb
  app/views/layouts/application.html.erb
  config/routes/claims.rb
  spec/helpers/routes_helper_spec.rb
Labels: deploy

#441 Redirect users to their respective homepages when visiting the root path
  app/controllers/application_controller.rb
  app/controllers/claims/pages_controller.rb
  app/controllers/sessions_controller.rb
  spec/system/claims/start_page_spec.rb
Labels: deploy

#446 Create sandbox environment
  .github/workflows/build_and_deploy.yml
  Makefile
  global_config/sandbox.sh
  terraform/application/config/sandbox.tfvars.json
  terraform/application/config/sandbox_Terrafile
  terraform/application/config/sandbox_app_env.yml
Labels: devops

#447 Support claims index page filters
  app/assets/images/icon-magnifying-glass.svg
  app/assets/stylesheets/filter-form.scss
  app/components/claim/card_component.html.erb
  app/controllers/claims/support/claims_controller.rb
  app/forms/claims/support/claims/filter_form.rb
  app/javascript/controllers/claims_support_filter_search_controller.js
  app/javascript/controllers/index.js
  app/queries/claims/claims_query.rb
  app/views/claims/support/claims/_filter.html.erb
  app/views/claims/support/claims/index.html.erb
  config/locales/en.yml
  config/locales/en/claims/support/claims.yml
  spec/components/claim/card_component_spec.rb
  spec/forms/claims/support/claims/filter_form_spec.rb
  spec/queries/claims/claims_query_spec.rb
  spec/system/claims/support/claims/view_claims_spec.rb
Labels: deploy

#485 Make the claims filters responsive
  app/assets/stylesheets/filter-form.scss
  app/assets/stylesheets/search-form.scss
  app/javascript/controllers/filter_controller.js
  app/javascript/controllers/index.js
  app/views/claims/support/claims/_filter.html.erb
  app/views/claims/support/claims/index.html.erb
  config/locales/en.yml
Labels: deploy

#489 Update Claim details pages
  app/assets/stylesheets/components/_all.scss
  app/assets/stylesheets/components/_heading.scss
  app/views/claims/schools/claims/show.html.erb
  app/views/claims/support/claims/_details.html.erb
  app/views/claims/support/claims/show.html.erb
  app/views/claims/support/schools/claims/show.html.erb
  config/locales/en/claims/schools/claims.yml
  config/locales/en/claims/support/claims.yml
  config/locales/en/claims/support/schools/claims.yml
  spec/system/claims/schools/claims/view_claim_spec.rb
  spec/system/claims/support/claims/view_a_claim_spec.rb
  spec/system/claims/support/schools/claims/view_claim_spec.rb
Labels: deploy

#491 Add auth/failure route
  app/controllers/sessions_controller.rb
  config/routes.rb
  spec/requests/sessions_spec.rb
  spec/support/dfe_sign_in_user_helper.rb
  spec/support/omniauth.rb
  spec/system/claims/sign_in_as_a_claims_user_spec.rb
  spec/system/placements/sign_in_as_a_placements_user_spec.rb
Labels: deploy

#493 Added workflow for manual deployments
  .github/workflows/deploy.yml
Labels: devops

#497 Use the FormObject directly when adding a provider to a claim
  app/controllers/claims/schools/claims_controller.rb
  app/controllers/claims/support/schools/claims_controller.rb
  app/forms/claims/claim/provider_form.rb
  config/locales/en/activemodel.yml
  spec/forms/claims/claim/provider_form_spec.rb
Labels: deploy

#495 Update not_an_integer error message for mentor training hours
  config/locales/en/activerecord.yml
  spec/system/claims/schools/claims/create_claim_spec.rb
  spec/system/claims/support/schools/claims/create_claim_spec.rb
Labels: deploy

#494 Update ApplicationMailer to use "https" protocol for default url options in production and add CLAIM_HOST
  app/mailers/application_mailer.rb
  spec/mailers/application_mailer_spec.rb
  terraform/application/config/qa_app_env.yml
  terraform/application/config/sandbox_app_env.yml
  terraform/application/config/staging_app_env.yml
Labels: deploy

#499 Bug fix to pass sha
  .github/workflows/deploy.yml
Labels: devops

#506 Bug fix for Slack trigger
  .github/workflows/deploy.yml
Labels: devops

#504 Allow user to select ANY school or provider to create a partnership
  app/controllers/api/placements/provider_suggestions_controller.rb
  app/controllers/api/placements/school_suggestions_controller.rb
  app/controllers/api/provider_suggestions_controller.rb
  app/controllers/api/school_suggestions_controller.rb
  app/forms/placements/partnership_form.rb
  app/models/placements/partnership.rb
  app/views/placements/providers/partner_schools/new.html.erb
  app/views/placements/schools/partner_providers/new.html.erb
  spec/forms/placements/partnership_form_spec.rb
  spec/models/placements/provider_spec.rb
  spec/models/placements/school_spec.rb
Labels: deploy

#511 As a User & Support User, I want to see the breakdown of the claim amount
  app/views/claims/schools/claims/check.html.erb
  app/views/claims/schools/claims/show.html.erb
  app/views/claims/support/claims/_details.html.erb
  app/views/claims/support/schools/claims/check.html.erb
  config/locales/en/claims/schools/claims.yml
  config/locales/en/claims/support/claims.yml
  config/locales/en/claims/support/schools/claims.yml
  spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb
  spec/system/claims/schools/claims/create_claim_spec.rb
  spec/system/claims/schools/claims/view_claim_spec.rb
  spec/system/claims/support/claims/view_a_claim_spec.rb
  spec/system/claims/support/schools/claims/view_claim_spec.rb
Labels: deploy

#527 Add Proof of Concept for responsive tables
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/utils/_all.scss
  app/assets/stylesheets/utils/_overflow.scss
  app/views/claims/schools/claims/index.html.erb
Labels: deploy

#538 Enabled azure backup storage for staging
  terraform/application/config/production.tfvars.json
  terraform/application/config/staging.tfvars.json
Labels: devops

#534 Force and assume SSL
  config/environments/production.rb
Labels: deploy

#535 Add CSP headers
  config/initializers/content_security_policy.rb
Labels: deploy

#543 Production db backup workflow
  .github/workflows/database-backup.yml
Labels: devops

#531 Jc/provider find placements
  app/assets/stylesheets/components/_all.scss
  app/assets/stylesheets/components/_organisation_list_item.scss
  app/assets/stylesheets/components/_search_results.scss
  app/components/placement/summary_component.html.erb
  app/components/placement/summary_component.rb
  app/controllers/placements/providers/placements_controller.rb
  app/decorators/school_decorator.rb
  app/forms/placements/placements/filter_form.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/placements_filter_search_controller.js
  app/models/placement.rb
  app/models/school.rb
  app/queries/placements/placements_query.rb
  app/views/placements/providers/_primary_navigation.html.erb
  app/views/placements/providers/placements/_filter.html.erb
  app/views/placements/providers/placements/index.html.erb
  config/locales/en/components/placement/summary_component.yml
  config/locales/en/placements/providers/placements.yml
  config/routes/placements.rb
  spec/components/placement/summary_component_spec.rb
  spec/components/previews/placement/summary_component_preview.rb
  spec/decorators/school_decorator_spec.rb
  spec/forms/placements/placements/filter_form_spec.rb
  spec/models/placement_spec.rb
  spec/models/school_spec.rb
  spec/system/placements/providers/placements/view_placements_list_spec.rb
Labels: deploy

#540 Update styling and content of school lists
  app/components/organisation_list_item.html.erb
  app/components/organisation_list_item.rb
  app/views/claims/schools/index.html.erb
  app/views/placements/support/organisations/index.html.erb
Labels: deploy

#541 Add show page for provider placements
  app/components/placement/summary_component.html.erb
  app/components/placement/summary_component.rb
  app/controllers/placements/providers/placements_controller.rb
  app/decorators/placement_decorator.rb
  app/views/placements/providers/placements/_mentor_details.html.erb
  app/views/placements/providers/placements/_school_details.html.erb
  app/views/placements/providers/placements/index.html.erb
  app/views/placements/providers/placements/show.html.erb
  config/locales/en/placements/providers/placements.yml
  config/routes/placements.rb
  spec/components/placement/summary_component_spec.rb
  spec/components/previews/placement/summary_component_preview.rb
  spec/system/placements/providers/placements/view_a_placement_spec.rb
Labels: deploy

#539 [RFC] Create app_table helper to extend govuk_table helper
  app/helpers/table_helper.rb
  app/views/claims/pages/cookies.html.erb
  app/views/claims/schools/_grant_conditions.html.erb
  app/views/claims/schools/claims/index.html.erb
  app/views/claims/schools/mentors/index.html.erb
  app/views/claims/schools/users/index.html.erb
  app/views/claims/support/schools/claims/index.html.erb
  app/views/claims/support/schools/mentors/index.html.erb
  app/views/claims/support/support_users/index.html.erb
  app/views/placements/organisations/users/_list.html.erb
  app/views/placements/providers/partner_schools/index.html.erb
  app/views/placements/schools/mentors/index.html.erb
  app/views/placements/schools/partner_providers/index.html.erb
  app/views/placements/schools/placements/index.html.erb
  app/views/placements/support/providers/users/index.html.erb
  app/views/placements/support/schools/mentors/index.html.erb
  app/views/placements/support/schools/placements/index.html.erb
  app/views/placements/support/schools/users/index.html.erb
  app/views/placements/support/support_users/index.html.erb
Labels: deploy

#554 Update grant conditions path to "/grant-conditions"
  config/routes/claims.rb
  spec/helpers/footer_helper_spec.rb
Labels: deploy

#542 Ask for DOB when adding a claim mentor
  .env.example
  .env.test
  app/controllers/claims/schools/mentors_controller.rb
  app/controllers/claims/support/schools/mentors_controller.rb
  app/forms/claims/mentor_form.rb
  app/services/claims/mentor_builder.rb
  app/services/teaching_record/get_teacher.rb
  app/services/teaching_record/rest_client.rb
  app/views/claims/schools/mentors/check.html.erb
  app/views/claims/schools/mentors/new.html.erb
  app/views/claims/support/schools/mentors/check.html.erb
  app/views/claims/support/schools/mentors/new.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/claims/schools/mentors.yml
  config/locales/en/claims/support/schools/mentors.yml
  spec/jobs/teaching_record/sync_mentor_job_spec.rb
  spec/services/claims/mentor_builder_spec.rb
  spec/services/teaching_record/get_teacher_spec.rb
  spec/system/claims/schools/mentors/add_a_mentor_spec.rb
  spec/system/claims/support/schools/mentors/support_user_adds_a_mentor_spec.rb
  terraform/application/config/dv_review_app_env.yml
  terraform/application/config/production_app_env.yml
  terraform/application/config/qa_app_env.yml
  terraform/application/config/review_app_env.yml
  terraform/application/config/sandbox_app_env.yml
  terraform/application/config/staging_app_env.yml
Labels: deploy

#566 Disable DfE Analytics for the healthcheck endpoint
  app/controllers/heartbeat_controller.rb
  spec/requests/dfe_analytics_spec.rb
Labels: deploy

#551 [1685] Ship logs to Logit.io
  terraform/application/application.tf
Labels: deploy, devops

#564 Update the claims feedback url
  app/helpers/routes_helper.rb
  spec/helpers/routes_helper_spec.rb
Labels: deploy

#561 Update terms page
  app/views/claims/pages/terms.en.html.erb
  app/views/claims/pages/terms.html.erb
  config/locales/en/claims/pages.yml
Labels: deploy

#563 Reject claims with invalid mentor training hours
  app/controllers/claims/schools/claims_controller.rb
  app/controllers/claims/support/schools/claims_controller.rb
  app/models/claims/claim.rb
  app/policies/claims/claim_policy.rb
  app/views/claims/schools/claims/rejected.html.erb
  app/views/claims/support/schools/claims/rejected.html.erb
  config/locales/en/claims/schools/claims.yml
  config/locales/en/claims/support/schools/claims.yml
  config/routes/claims.rb
  spec/models/claims/claim_spec.rb
  spec/policies/claims/claim_policy_spec.rb
  spec/system/claims/schools/claims/create_claim_spec.rb
  spec/system/claims/support/schools/claims/create_claim_spec.rb
Labels: deploy
