Repository DFE-Digital/itt-mentor-services, pull requests merged in 2024-09, with the labels that each got.

#974 Remove unnecessary fields from provider placements index view
  app/components/placement/summary_component.html.erb
  spec/components/placement/summary_component_spec.rb
Labels: deploy

#969 UI changes to placements show page
  app/decorators/placement_decorator.rb
  app/views/placements/schools/placements/_details.html.erb
  config/locales/en/placements/schools/placements.yml
  spec/system/placements/schools/placements/view_a_placement_spec.rb
Labels: deploy

#986 Update claim window seed
  db/seeds.rb
Labels: deploy

#905 Select academic year when creating a claim window
  app/controllers/claims/support/claim_windows_controller.rb
  app/forms/application_form.rb
  app/forms/claims/claim_window_form.rb
  app/forms/concerns/date_attributes.rb
  app/models/claims/claim_window.rb
  app/validators/date_presence_validator.rb
  app/views/claims/support/claim_windows/edit.html.erb
  app/views/claims/support/claim_windows/edit_check.html.erb
  app/views/claims/support/claim_windows/new.html.erb
  app/views/claims/support/claim_windows/new_check.html.erb
  app/views/claims/support/claim_windows/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/activerecord.yml
  config/locales/en/claims/support/claim_windows.yml
  spec/forms/application_form_spec.rb
  spec/forms/claims/claim_window_form_spec.rb
  spec/models/claims/claim_window_spec.rb
  spec/system/claims/support/create_a_claim_window_spec.rb
  spec/system/claims/support/update_a_claim_window_spec.rb
Labels: deploy

#977 Redirect to organisations_path if current organisation is absent
  app/controllers/placements/placements_controller.rb
  spec/requests/placements/providers/placements_spec.rb
Labels: deploy

#995 Add status and type of establishment headers and outputs to CSV
  app/services/claims/claim/generate_csv.rb
  spec/services/claims/claim/generate_csv_spec.rb
Labels: deploy

#993 Fix maintenance page temp ingress url
  terraform/application/config/production_app_env.yml
  terraform/application/config/staging_app_env.yml
Labels: devops

#1001 DR test workflow improvements
  .github/workflows/database-backup.yml
  .github/workflows/postgres-ptr.yml
  .github/workflows/postgres-restore.yml
Labels: devops

#1006 Update claim confirmation content to latest dates
  config/locales/en/claims/schools/claims.yml
  spec/system/claims/schools/claims/create_claim_spec.rb
Labels: deploy

#999 DateAttributes should return nil when all date components are nil
  app/forms/concerns/date_attributes.rb
  spec/forms/application_form_spec.rb
Labels: deploy

#1026 Remove nulldb AR adapter
  .github/actions/deploy-environment/action.yml
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: deploy

#1027 Add the "sent_to_esfa" claim status
  app/models/claims/claim.rb
  config/initializers/inflections.rb
  db/migrate/20240913143256_add_sent_to_esfa_to_claim_status_enum.rb
  db/schema.rb
  spec/helpers/claims/claim_helper_spec.rb
  spec/models/claims/claim_spec.rb
Labels: deploy

#1032 Drop all encrypted data files and related services
  lib/data/schools.csv.enc
  lib/data/schools_with_emails.csv.enc
  lib/tasks/claims.rake
  lib/tasks/update_school_emails.rake
  spec/tasks/claims_spec.rb
  spec/tasks/update_schools_emails_spec.rb
Labels: deploy

#1013 add workflow dispatch to delete-review-app
  .github/workflows/delete_review_app.yml
Labels: deploy, devops

#1038 Replace H4 in content header component with span
  app/components/content_header_component.html.erb
Labels: deploy

#1040 "Show filter" button added to Support user -> organisation index
  app/views/placements/support/organisations/_filter.html.erb
  app/views/placements/support/organisations/index.html.erb
Labels: deploy

#1041 Remove the tag from the reset database page title
  app/assets/stylesheets/components/_all.scss
  app/assets/stylesheets/components/_tag.scss
  app/views/claims/support/databases/reset.en.html.erb
  spec/system/claims/support/reset_database_spec.rb
Labels: deploy

#1042 Downcase the environment name on the Claims reset database page
  app/views/claims/support/databases/reset.en.html.erb
  spec/system/claims/support/reset_database_spec.rb
Labels: deploy

#1045 Add visually hidden labels to filter search inputs
  app/javascript/controllers/filter_search_controller.js
  spec/system/claims/support/claims/view_claims_spec.rb
  spec/system/placements/placements/searches_filter_options_for_placements_spec.rb
Labels: deploy

#1048 Use mobile navigation on tablet viewports
  app/assets/stylesheets/components/_header.scss
Labels: deploy

#1014 Create training allowance object
  app/models/claims/training_allowance.rb
  spec/models/claims/training_allowance_spec.rb
Labels: deploy

#1065 Tweak claims status filters to use humanize instead of titleize
  app/views/claims/support/claims/_filter.html.erb
Labels: deploy

#1070 Upgrade to ruby 3.3.5
  .github/actions/deploy-environment/action.yml
  .github/workflows/build_and_test.yml
  .ruby-version
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: deploy
